openapi: 3.1.0
x-stoplight:
  id: rilex5rogslu3
info:
  title: kluwypay-bo-api
  version: '1.0'
  summary: API Back Office KluwyPay
  contact:
    name: Joandi
    url: '-'
    email: '-'
  termsOfService: '-'
  description: API Back Office KluwyPay
servers:
  - url: 'http://localhost:8080'
    description: LocalServer
  - description: DevServer
    url: 'https://api-bo.kluwypay.com'
paths:
  /auth:
    post:
      summary: POST auth
      operationId: generateToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  username: superadmin@kluwypay.com
                  password: superadmin
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            examples:
              superadmin:
                value:
                  username: superadmin@kluwypay.com
                  password: superadmin
              finance:
                value:
                  username: finance@kluwypay.com
                  password: finance
              support:
                value:
                  username: support@kluwypay.com
                  password: support
        required: true
        description: username dan password terdaftar...
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGtsdXd5cGF5LmNvbSIsImV4cCI6MTY2MDA5MjMzNSwiaWF0IjoxNjYwMDU2MzM1fQ.bFyesrGQqvDyboWvKTT5kpMAYvxEblHLgfG2f2bs5xk
                    status: OK
              examples:
                OK:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluQGtsdXd5cGF5LmNvbSIsImV4cCI6MTY2MDA5MjMzNSwiaWF0IjoxNjYwMDU2MzM1fQ.bFyesrGQqvDyboWvKTT5kpMAYvxEblHLgfG2f2bs5xk
                    status: OK
                Invalid Username Or Password:
                  value:
                    token: ''
                    status: invalid username / password
      description: Melakukan generate JWT Token berdasarkan username & password pair yg terdaftar di database
      tags:
        - auth
      security: []
  /api/account/list:
    get:
      summary: GET Account List
      operationId: account_list
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      security:
        - JWTToken: []
      tags:
        - account
      description: |
        get account list registered in database
  /api/bank/list:
    get:
      summary: GET Bank List
      operationId: bank_list
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: get bank list registered in database
      tags:
        - bank
  /api/bank/create:
    post:
      summary: Create Bank
      operationId: bank_create
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      tags:
        - bank
      description: create new bank
  /api/bank/update:
    post:
      summary: Update Bank
      operationId: bank_update
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      tags:
        - bank
      description: update bank
  /api/bank/delete:
    get:
      summary: Delete Bank
      operationId: bank_delete
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      tags:
        - bank
      description: delete bank
  /api/channel/list:
    get:
      summary: GET Channel List
      operationId: channel_list
      parameters:
        - name: start
          in: query
          schema:
            type: integer
            format: int32
        - name: length
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
      security:
        - JWTToken: []
      description: get channel list
      tags:
        - channel
  /api/channel/create:
    post:
      summary: Create New Channel
      operationId: channel_create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ntid:
                  type: string
                chname:
                  type: string
                feetype:
                  type: string
                chfee:
                  type: integer
                state:
                  type: boolean
              x-examples:
                example-1:
                  ntid: 06fd799c-fa56-4c88-b868-611725ed69da
                  chname: qris
                  feetype: fixed
                  chfee: 2000
                  state: true
            examples:
              sample:
                value:
                  ntid: 06fd799c-fa56-4c88-b868-611725ed69da
                  chname: qris
                  feetype: fixed
                  chfee: 2000
                  state: true
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: Network Not Found
                    status: '0002'
              examples:
                Network Not Found:
                  value:
                    data: {}
                    message: Network Not Found
                    status: '0002'
                OK:
                  value:
                    data: {}
                    message: OK
                    status: '0001'
      tags:
        - channel
      description: Create New Channel
  /api/channel/update:
    post:
      summary: Update Channel
      operationId: channel_update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                ntid:
                  type: string
                chname:
                  type: string
                feetype:
                  type: string
                chfee:
                  type: integer
                state:
                  type: boolean
              x-examples:
                example-1:
                  id: e29b2f49-285b-4341-94b4-94e92be7b483
                  ntid: 06fd799c-fa56-4c88-b868-611725ed69da
                  chname: qris
                  feetype: fixed
                  chfee: 2000
                  state: true
            examples:
              Sample:
                value:
                  id: e29b2f49-285b-4341-94b4-94e92be7b483
                  ntid: 06fd799c-fa56-4c88-b868-611725ed69da
                  chname: qris
                  feetype: fixed
                  chfee: 2000
                  state: true
        required: true
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      tags:
        - channel
      description: Update Channel
  /api/channel/delete:
    get:
      summary: Delete Channel
      operationId: channel_delete
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
      tags:
        - channel
      description: Delete Channel
  /api/fee/list:
    get:
      summary: Fee List
      operationId: fee_list
      parameters:
        - name: start
          in: query
          schema:
            type: integer
            format: int32
        - name: length
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            pcode:
                              type: string
                            trxtype:
                              type: string
                            feeside:
                              type: string
                            feename:
                              type: string
                            feetype:
                              type: string
                            feeamount:
                              type: integer
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data:
                      total: 2
                      items:
                        - id: 84cf9bb6-ad5b-441f-af2d-e4483184a496
                          pcode: PTAR
                          trxtype: deposit
                          feeside: kreditor
                          feename: Biaya Upeti
                          feetype: fixed
                          feeamount: 50000
                        - id: ef46e2e9-addc-4b14-a45a-68835e281fe3
                          pcode: PTAR
                          trxtype: deposit
                          feeside: kreditor
                          feename: Biaya Upeti
                          feetype: fixed
                          feeamount: 50000
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data:
                      total: 2
                      items:
                        - id: 84cf9bb6-ad5b-441f-af2d-e4483184a496
                          pcode: PTAR
                          trxtype: deposit
                          feeside: kreditor
                          feename: Biaya Upeti
                          feetype: fixed
                          feeamount: 50000
                        - id: ef46e2e9-addc-4b14-a45a-68835e281fe3
                          pcode: PTAR
                          trxtype: deposit
                          feeside: kreditor
                          feename: Biaya Upeti
                          feetype: fixed
                          feeamount: 50000
                    message: OK
                    status: '0001'
      tags:
        - fee
      description: mengambil fee list
      security: []
  /api/fee/create:
    post:
      summary: Fee Create
      operationId: fee_create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pid:
                  type: string
                feetype:
                  type: string
                feeside:
                  type: string
                feedesc:
                  type: string
                feeamount:
                  type: integer
                trxtype:
                  type: string
                chid:
                  type: string
              x-examples:
                example-1:
                  pid: c12d762d-52ba-443a-8528-48cd9b8a867d
                  feetype: fixed
                  feeside: kreditor
                  feedesc: Biaya Layanan
                  feeamount: 50000
                  trxtype: deposit
                  chid: c12d762d-52ba-443a-8528-48cd9b8a867d
            examples:
              Sample:
                value:
                  pid: f3c223d1-085f-4a33-8caa-9015dd029bc4
                  feename: Biaya Layanan
                  feetype: fixed
                  feeside: kreditor
                  feeamount: 50000
                  trxtype: deposit
                  chid: e29b2f49-285b-4341-94b4-94e92be7b483
        required: true
        description: semua kolom required
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: Channel Not Found
                    status: '0003'
              examples:
                OK:
                  value:
                    data: {}
                    message: OK
                    status: '0001'
                Channel Not Found:
                  value:
                    data: {}
                    message: Channel Not Found
                    status: '0003'
                Partner Not Found:
                  value:
                    data: {}
                    message: Partner Not Found
                    status: '0002'
      tags:
        - fee
      description: membuat fee
      security:
        - JWTToken: []
  /api/fee/update:
    post:
      summary: Fee Update
      operationId: fee_update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                pid:
                  type: string
                feename:
                  type: string
                feetype:
                  type: string
                feeside:
                  type: string
                feeamount:
                  type: integer
                trxtype:
                  type: string
                chid:
                  type: string
              x-examples:
                example-1:
                  id: 2b510468-a2b9-4b12-b30c-04fe50d81967
                  pid: f3c223d1-085f-4a33-8caa-9015dd029bc4
                  feename: Biaya Denda
                  feetype: fixed
                  feeside: kreditor
                  feeamount: 50000
                  trxtype: deposit
                  chid: e29b2f49-285b-4341-94b4-94e92be7b483
            examples:
              Sample:
                value:
                  id: 2b510468-a2b9-4b12-b30c-04fe50d81967
                  pid: f3c223d1-085f-4a33-8caa-9015dd029bc4
                  feename: Biaya Denda
                  feetype: fixed
                  feeside: kreditor
                  feeamount: 50000
                  trxtype: deposit
                  chid: e29b2f49-285b-4341-94b4-94e92be7b483
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data: {}
                    message: OK
                    status: '0001'
                Channel Not Found:
                  value:
                    data: {}
                    message: Channel Not Found
                    status: '0003'
                Partner Not Found:
                  value:
                    data: {}
                    message: string
                    status: string
                Fee Not Found:
                  value:
                    data: {}
                    message: Fee Not Found
                    status: '0004'
      tags:
        - fee
      description: mengupdate fee
  /api/fee/delete:
    get:
      summary: Fee delete
      operationId: fee_delete
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data: {}
                    message: OK
                    status: '0001'
                Fee Not Found:
                  value:
                    message: Fee Not Found
                    status: '0002'
      tags:
        - fee
      description: menghapus fee
  /api/network/list:
    get:
      summary: Network List
      operationId: network_list
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 1
          description: halaman ke berapa
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 5
          description: jumlah record per halaman
        - schema:
            type: string
          in: query
          name: ntname
          description: mencari yg name nya ada mengandung string nganu
        - schema:
            type: string
            default: asc
          in: query
          name: sort
          description: '''asc'' apa ''desc'''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            ntname:
                              type: string
                            ntcode:
                              type: string
                            channelCount:
                              type: integer
                            createdtime:
                              type: string
                            updatedtime:
                              type: string
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data:
                      total: 5
                      items:
                        - id: 0f711e80-8151-4c73-9f70-4166ec703317
                          ntname: Telkomsel
                          ntcode: TSEL
                          channelCount: 1
                          createdtime: '2022-08-13 08:22:31'
                          updatedtime: '2022-08-13 08:22:31'
                        - id: 2e17bd5c-b605-4973-9e3a-47d8483a63d5
                          ntname: Telkomsel
                          ntcode: TSEL
                          channelCount: 0
                          createdtime: '2022-08-12 06:06:02'
                          updatedtime: '2022-08-13 13:02:44'
                        - id: 57aa514b-fdc8-41e3-8d1b-cafefc78564b
                          ntname: asd
                          ntcode: '1'
                          channelCount: 0
                          createdtime: '2022-08-11 10:26:10'
                          updatedtime: '2022-08-11 10:26:10'
                        - id: f4b3ed67-7403-4d62-97d7-90241ba46bfe
                          ntname: asd
                          ntcode: '123'
                          channelCount: 0
                          createdtime: '2022-08-11 12:24:52'
                          updatedtime: '2022-08-11 12:24:52'
                        - id: 61d9ea23-a688-4461-99c2-0a984c6be5f1
                          ntname: asd
                          ntcode: '123'
                          channelCount: 0
                          createdtime: '2022-08-12 02:59:21'
                          updatedtime: '2022-08-12 02:59:21'
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data:
                      total: 5
                      items:
                        - id: 0f711e80-8151-4c73-9f70-4166ec703317
                          ntname: Telkomsel
                          ntcode: TSEL
                          channelCount: 1
                          createdtime: '2022-08-13 08:22:31'
                          updatedtime: '2022-08-13 08:22:31'
                        - id: 2e17bd5c-b605-4973-9e3a-47d8483a63d5
                          ntname: Telkomsel
                          ntcode: TSEL
                          channelCount: 0
                          createdtime: '2022-08-12 06:06:02'
                          updatedtime: '2022-08-13 13:02:44'
                        - id: 57aa514b-fdc8-41e3-8d1b-cafefc78564b
                          ntname: asd
                          ntcode: '1'
                          channelCount: 0
                          createdtime: '2022-08-11 10:26:10'
                          updatedtime: '2022-08-11 10:26:10'
                        - id: f4b3ed67-7403-4d62-97d7-90241ba46bfe
                          ntname: asd
                          ntcode: '123'
                          channelCount: 0
                          createdtime: '2022-08-11 12:24:52'
                          updatedtime: '2022-08-11 12:24:52'
                        - id: 61d9ea23-a688-4461-99c2-0a984c6be5f1
                          ntname: asd
                          ntcode: '123'
                          channelCount: 0
                          createdtime: '2022-08-12 02:59:21'
                          updatedtime: '2022-08-12 02:59:21'
                    message: OK
                    status: '0001'
      description: mengambil daftar network dari database
      tags:
        - network
      security:
        - JWTToken: []
  /api/network/create:
    post:
      summary: Network Create
      operationId: network_create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ntname:
                  type: string
                ntcode:
                  type: string
              x-examples:
                example-1:
                  ntname: Telkomsel
                  ntcode: TSEL
            examples:
              OK:
                value:
                  ntname: Telkomsel
                  ntcode: TSEL
          application/xml:
            schema:
              type: object
              properties: {}
        required: true
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                x-examples:
                  example-1:
                    status: OK
              examples:
                OK:
                  value:
                    status: OK
      security: []
      description: membuat network baru
      tags:
        - network
  /api/network/update:
    post:
      summary: Network Update
      operationId: network_update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                ntname:
                  type: string
                ntcode:
                  type: string
              x-examples:
                example-1:
                  id: 8d65b694-f1e6-4d43-a684-8fb7ebb96fcb
                  ntname: Telkomsel
                  ntcode: TSEL
            examples:
              Example:
                value:
                  id: 8d65b694-f1e6-4d43-a684-8fb7ebb96fcb
                  ntname: Telkomsel
                  ntcode: TSEL
          application/xml:
            schema:
              type: object
              properties: {}
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data: {}
                    message: OK
                    status: '0001'
                Network Not Found:
                  value:
                    data: {}
                    message: Network Not Found
                    status: '0002'
            application/xml:
              schema:
                type: object
                properties: {}
      security: []
      description: mengupdate data network dari database
      tags:
        - network
  /api/network/delete:
    get:
      summary: Network Delete
      operationId: network_delete
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data: {}
                    message: OK
                    status: '0001'
                Network Not Found:
                  value:
                    data: {}
                    message: Network Not Found
                    status: '0002'
      security:
        - JWTToken: []
      description: menghapus network
      tags:
        - network
  /api/network/channel:
    get:
      summary: Get Channel List By Network
      operationId: network_channel_list
      parameters:
        - name: nid
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            chname:
                              type: string
                            feetype:
                              type: string
                            chfee:
                              type: integer
                            createdtime:
                              type: string
                            updatedTime:
                              type: string
                            state:
                              type: boolean
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data:
                      total: 1
                      items:
                        - id: 6f7ed818-3d08-4345-b5d9-7d6b3cc9b5f7
                          chname: qris
                          feetype: fixed
                          chfee: 2000
                          createdtime: '2022-08-13 20:21:56'
                          updatedTime: '2022-08-13 20:21:56'
                          state: true
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data:
                      total: 1
                      items:
                        - id: 6f7ed818-3d08-4345-b5d9-7d6b3cc9b5f7
                          chname: qris
                          feetype: fixed
                          chfee: 2000
                          createdtime: '2022-08-13 20:21:56'
                          updatedTime: '2022-08-13 20:21:56'
                          state: true
                    message: OK
                    status: '0001'
                Network Not Found:
                  value:
                    data: {}
                    message: Network Not Found
                    status: '0002'
      security:
        - JWTToken: []
  /api/partner/list:
    get:
      summary: Partner LIST
      operationId: partner_list
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
          description: 'halaman berapa, dimulai dari 0'
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 5
          description: panjang record
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  size:
                    type: integer
                  page:
                    type: integer
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        pname:
                          type: string
                        pcode:
                          type: string
                        pemail:
                          type: 'null'
                        pphone:
                          type: 'null'
                        createdtime:
                          type: string
                        updatedtime:
                          type: string
                        state:
                          type: string
                x-examples:
                  example-1:
                    total: 4
                    size: 5
                    page: 0
                    content:
                      - id: 235e5428-84eb-4739-a977-f447cbf8908e
                        pname: PT. BINEKA
                        pcode: bsKAHUzg
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-07 13:22:34'
                        updatedtime: '2022-08-07 13:22:34'
                        state: active
                      - id: e2d0e8c9-c6e7-4b2d-a309-391a4d2331af
                        pname: PT. KLUWIPAY
                        pcode: asdfasdf
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-07 19:31:38'
                        updatedtime: '2022-08-07 19:31:42'
                        state: active
                      - id: d92bbec8-2507-497b-b861-02d5febfad49
                        pname: PT. BINEKKA
                        pcode: isVukDts
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-07 13:55:53'
                        updatedtime: '2022-08-07 13:55:53'
                        state: active
                      - id: 863b98e8-914f-40d1-b08a-3f1b51c975ae
                        pname: PT. COBA
                        pcode: NkBNZQCr
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-08 06:48:50'
                        updatedtime: '2022-08-08 06:48:50'
                        state: active
              examples:
                example:
                  value:
                    total: 4
                    size: 5
                    page: 0
                    content:
                      - id: 235e5428-84eb-4739-a977-f447cbf8908e
                        pname: PT. BINEKA
                        pcode: bsKAHUzg
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-07 13:22:34'
                        updatedtime: '2022-08-07 13:22:34'
                        state: active
                      - id: e2d0e8c9-c6e7-4b2d-a309-391a4d2331af
                        pname: PT. KLUWIPAY
                        pcode: asdfasdf
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-07 19:31:38'
                        updatedtime: '2022-08-07 19:31:42'
                        state: active
                      - id: d92bbec8-2507-497b-b861-02d5febfad49
                        pname: PT. BINEKKA
                        pcode: isVukDts
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-07 13:55:53'
                        updatedtime: '2022-08-07 13:55:53'
                        state: active
                      - id: 863b98e8-914f-40d1-b08a-3f1b51c975ae
                        pname: PT. COBA
                        pcode: NkBNZQCr
                        pemail: null
                        pphone: null
                        createdtime: '2022-08-08 06:48:50'
                        updatedtime: '2022-08-08 06:48:50'
                        state: active
      security: []
      description: ambil partner list dari database
      tags:
        - partner
  /api/partner/create:
    post:
      summary: Partner CREATE
      operationId: partner_create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pname:
                  type: string
                pcode:
                  type: string
                pemail:
                  type: string
                pphone:
                  type: string
                state:
                  type: string
              x-examples:
                example-1:
                  pname: PT Angin Ribut
                  pcode: PTAR
                  pemail: angin@ribut.com
                  pphone: 021-8207659
                  state: active
            examples:
              FULL Form:
                value:
                  pname: PT Angin Ribut
                  pcode: PTAR
                  pemail: angin@ribut.com
                  pphone: 021-8207659
                  state: active
        required: true
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                x-examples:
                  example-1:
                    status: OK
              examples:
                OK:
                  value:
                    status: OK
      description: create partner
      security: []
      tags:
        - partner
  /api/partner/update:
    post:
      summary: Partner UPDATE
      operationId: partner_update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                pname:
                  type: string
                pcode:
                  type: string
                pemail:
                  type: string
                pphone:
                  type: string
                state:
                  type: string
              x-examples:
                example-1:
                  id: e5e36346-16d2-4487-a3f3-9ecf644e58eb
                  pname: PT Angin Ribut
                  pcode: PTAR
                  pemail: angin@ribut.com
                  pphone: 021-8207659
                  state: active
            examples:
              OK:
                value:
                  id: e5e36346-16d2-4487-a3f3-9ecf644e58eb
                  pname: PT Angin Ribut
                  pcode: PTAB
                  pemail: angin@ribut.com
                  pphone: 021-8207659
                  state: active
        required: true
        description: element ID di array akan digunakan untuk me-retrieve data existing
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Update Partner
      security: []
      tags:
        - partner
  /api/partner/delete:
    get:
      summary: Partner DELETE
      operationId: partner_delete
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: partner id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    status: OK
                properties:
                  status:
                    type: string
              examples:
                OK:
                  value:
                    status: OK
      description: delete partner
      security: []
      tags:
        - partner
  /api/partner-channel/list:
    get:
      summary: Partner Channel List
      operationId: list
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      security:
        - JWTToken: []
  /api/partner-channel/create:
    post:
      summary: Create Partner Channel
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chid:
                  type: string
                pid:
                  type: string
                mid:
                  type: string
                tid:
                  type: string
                mname:
                  type: string
                maxamount:
                  type: integer
                minamount:
                  type: integer
                maxtrx:
                  type: integer
                status:
                  type: string
                maxvolume:
                  type: integer
                trxvolume:
                  type: integer
              x-examples:
                example-1:
                  chid: ''
                  pid: ''
                  mid: ''
                  tid: ''
                  mname: ''
                  maxamount: 0
                  minamount: 0
                  maxtrx: 0
                  status: ''
                  maxvolume: 0
                  trxvolume: 0
            examples:
              Sample:
                value:
                  chid: 6f7ed818-3d08-4345-b5d9-7d6b3cc9b5f7
                  pid: f3c223d1-085f-4a33-8caa-9015dd029bc4
                  mid: MID
                  tid: TID
                  mname: MNAME
                  maxamount: 12345678
                  minamount: 1234
                  maxtrx: 1000
                  status: active
                  maxvolume: 1000000
                  trxvolume: 500000
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    data: {}
                    message: OK
                    status: '0001'
                Channel Not Found:
                  value:
                    data: {}
                    message: Channel Not Found
                    status: '0003'
                Partner Not Found:
                  value:
                    data: {}
                    message: Partner Not Found
                    status: '0002'
  /api/partner-channel/update:
    post:
      summary: Update Partner Channel
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  id: ''
                  chid: ''
                  pid: ''
                  mid: ''
                  tid: ''
                  mname: ''
                  maxamount: 0
                  minamount: 0
                  maxtrx: 0
                  status: ''
                  maxvolume: 0
                  trxvolume: 0
              properties:
                id:
                  type: string
                chid:
                  type: string
                pid:
                  type: string
                mid:
                  type: string
                tid:
                  type: string
                mname:
                  type: string
                maxamount:
                  type: integer
                minamount:
                  type: integer
                maxtrx:
                  type: integer
                status:
                  type: string
                maxvolume:
                  type: integer
                trxvolume:
                  type: integer
              required:
                - id
            examples:
              sample:
                value:
                  id: 7f1b2591-c786-46b5-9966-1fda23bd1747
                  chid: 6f7ed818-3d08-4345-b5d9-7d6b3cc9b5f7
                  pid: f3c223d1-085f-4a33-8caa-9015dd029bc4
                  mid: MID
                  tid: TID
                  mname: MNAME
                  maxamount: 12345678
                  minamount: 1234
                  maxtrx: 1000
                  status: active
                  maxvolume: 1000000
                  trxvolume: 500000
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    data: {}
                    message: OK
                    status: '0001'
              examples:
                OK:
                  value:
                    id: 7f1b2591-c786-46b5-9966-1fda23bd1747
                    chid: 6f7ed818-3d08-4345-b5d9-7d6b3cc9b5f7
                    pid: f3c223d1-085f-4a33-8caa-9015dd029b4
                    mid: MID
                    tid: TID
                    mname: MNAME
                    maxamount: 12345678
                    minamount: 1234
                    maxtrx: 1000
                    status: active
                    maxvolume: 1000000
                    trxvolume: 500000
                Partner Not Found:
                  value:
                    data: {}
                    message: string
                    status: string
                Channel Not Found:
                  value:
                    data: {}
                    message: Channel Not Found
                    status: '0003'
                Partner Channel Not Found:
                  value:
                    data: {}
                    message: Partner Channel Not Found
                    status: '0004'
  /api/partner-channel/delete:
    get:
      summary: Delete Partner Channel
      operationId: delete
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
                x-examples:
                  example-1:
                    message: OK
                    status: '0001'
              examples:
                Partner Channel Not Found:
                  value:
                    message: Partner Channel Not Found
                    status: '0002'
                OK:
                  value:
                    message: OK
                    status: '0001'
components:
  securitySchemes:
    JWTToken:
      type: http
      scheme: bearer
tags:
  - name: account
  - name: auth
  - name: bank
  - name: channel
  - name: fee
  - name: network
  - name: partner
